# Generated by Django 5.0 on 2024-07-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=266)),
            ],
            options={
                "verbose_name": "chatuser",
                "verbose_name_plural": "chatusers",
            },
        ),
    ]
